a.out: main.o func1.o f2.o f3.o f4.o f5.o
	g++ -g main.o func1.o f2.o f3.o f4.o f5.o

main.o: main.cpp
	g++ -c -g main.cpp

func1.o: func1.cpp
	g++ -c -g func1.cpp

f2.o: f2.cpp
	g++ -c -g f2.cpp

f3.o: f3.cpp
	g++ -c -g f3.cpp

f4.o: f4.cpp
	g++ -c -g f4.cpp

f5.o: f5.cpp
	g++ -c -g f5.cpp


