a.exe: main.o selection_sort.o quicksort.o
	g++ -g main.o selection_sort.o quicksort.o

selection_sort.o: selection_sort.cpp 
	g++ -c -g selection_sort.cpp

quicksort.o: quicksort.cpp
	g++ -c -g quicksort.cpp

main.o: main.cpp
	g++ -c -g main.cpp